[package]
name = "lockpick"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
permute = "0.2.1"
=======
>>>>>>> f8520d6 (initial tm commit)
